### ISSUE TITLE
DateTime not converting to "POSIXct" when importing turbidity data (Data Level 1)

### ISSUE THREAD

**Issue by nicole-hucke** [mayousif/Turbidity-Cleaner#2]
Hello! I am running Turbidity-Cleaner-3.1 in R-3.5.3. 

I followed all setup instructions and successfully ran the RunProgram.cmd file. 

When importing my turbidity data in the required format and structure specified in the README.md, I encountered the following message on the cmd.exe window: 

**_Listening on http://127.0.0.1:3054
Warning: Error in as.POSIXct.default: do not know how to convert 'TurbidityLVL1$DateTime' to class "POSIXct"
  1: runApp_**

Attached is the turbidity .csv file I tried submitting and am not sure where this problem might be coming from.
[SP23_LaJara_DownstreamTurbidity.csv](https://github.com/mayousif/Turbidity-Cleaner/files/14891803/SP23_LaJara_DownstreamTurbidity.csv)

Any help with this issue is greatly appreciated, thank you so much! :blush:

PS: If csv file is opened in excel, it might change the format of the DateTime column, it's best to view in text editor for the actual format it is in.
PPS: Here is the full message from the cmd.exe window just in case: 

```
C:\Users\huck4481\Documents\Turbidity-Cleaner-3.1>"C:\Program Files\R\R-3.5.3\bin\Rscript.exe" "C:/Users/huck4481/Documents/Turbidity-Cleaner-3.1/shiny/run.R" 
Attaching package: 'dplyr'

The following objects are masked from 'package:stats':
    filter, lag

The following objects are masked from 'package:base':
    intersect, setdiff, setequal, union

Attaching package: 'shinyjs'
The following object is masked from 'package:shinyWidgets':
    alert

The following object is masked from 'package:shiny':
    runExample

The following objects are masked from 'package:methods':
    removeClass, show

Loading required package: bit
Attaching package: 'bit'
The following object is masked from 'package:base':
    xor

Attaching package ff
- getOption("fftempdir")=="C:/Users/huck4481/AppData/Local/Temp/Rtmpod1qhI"
- getOption("ffextension")=="ff"
- getOption("ffdrop")==TRUE
- getOption("fffinonexit")==TRUE
- getOption("ffpagesize")==65536
- getOption("ffcaching")=="mmnoflush"  -- consider "ffeachflush" if your system stalls on large writes
- getOption("ffbatchbytes")==171284889.6 -- consider a different value for tuning your system
- getOption("ffmaxbytes")==8564244480 -- consider a different value for tuning your system

Attaching package: 'ff'
The following objects are masked from 'package:bit':
    clone, maxindex, poslength

The following objects are masked from 'package:utils':
    write.csv, write.csv2

The following objects are masked from 'package:base':
    is.factor, is.ordered

Attaching package: 'lubridate'
The following objects are masked from 'package:base':
    date, intersect, setdiff, union

Loading required package: zoo
Attaching package: 'zoo'
The following objects are masked from 'package:base':
    as.Date, as.Date.numeric

Attaching package: 'xts'
The following objects are masked from 'package:dplyr':
    first, last

*** This is beta software. Please report any bugs!
*** See the NEWS file for recent changes.

Attaching package: 'mice'
The following objects are masked from 'package:base':
    cbind, rbind

Listening on http://127.0.0.1:3054
**Warning: Error in as.POSIXct.default: do not know how to convert 'TurbidityLVL1$DateTime' to class "POSIXct"
  1: runApp**
```

**Comment by mayousif** [comment]
Hi Nicole!

It seems that the problem is the encoding of the .csv file. Since it is UTF-8 BOM encoded, the DateTime column name looks like this in R:

![image](https://github.com/mayousif/Turbidity-Cleaner/assets/48215235/5a7426c0-51c9-4e56-96e6-7fd1cafc0ad3)

If it isn't easy to set the encoding to "UTF-8" for your data, the fix would be to explicitly define the encoding of the read.csv function on lines lines 59 and 112 of server.R like so:

TurbidityLVL1 <<- read.csv(input$turb1file$datapath, fileEncoding="UTF-8-BOM")

Changing the code to this allowed me to run level 1 of the program with your sample data.

Let me know if you have any other questions!

**Comment by nicole-hucke** [comment]
Thank you so much for getting back to me! 

The encryption was definitely the issue. I tried it again in UTF-8 and it worked perfectly. 

Thank you again!
